# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160418_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_title']},
        ),
    ]
