# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160425_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
