# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
